// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package memberships is a generated GoMock package.
package memberships

import (
	reflect "reflect"

	memberships "github.com/NXRts/music-catalog/internal/models/memberships"
	gomock "github.com/golang/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// SingUp mocks base method.
func (m *Mockservice) SingUp(request memberships.SingUpRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SingUp", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// SingUp indicates an expected call of SingUp.
func (mr *MockserviceMockRecorder) SingUp(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SingUp", reflect.TypeOf((*Mockservice)(nil).SingUp), request)
}
